# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: words
    build: .
    command: gunicorn -b 0.0.0.0:5000 words.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=localhost
    volumes:
      - ./words:/code/words
      - ./db/:/db/
    ports:
      - "5000:5000"

  redis:
    image: redis:alpine
